spring:
  # 数据库配置----------------
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://101.200.205.9:3306/fruit?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 101.200.205.9
    port: 6379
server:
  port: 8080

